"""
user_service Service - Generated by EVOX
"""

from evox import service, get, post, delete, Param, Query, Body, Intent, auth, data_io

svc = service("user_service") \
    .port(8000) \
    .build()

@get("/hello")
async def hello():
    return {"message": "Hello from user_service service!"}

if __name__ == "__main__":
    svc.run(dev=True)
